
services:
  database:
    mem_limit: 2048m
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - joomla-network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - joomla-network

  joomla:
    depends_on:
      - database
    image: joomla:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file: .env
    environment:
      JOOMLA_DB_HOST: database
      JOOMLA_DB_NAME: ${MYSQL_DATABASE}
      JOOMLA_DB_USER: ${MYSQL_USER}
      JOOMLA_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - joomla_data:/var/www/html
      - ./docker/php/joomla.ini:/usr/local/etc/php/conf.d/zz-joomla.ini:ro
      - joomla_php_tmp:/tmp/php
    networks:
      - joomla-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - joomla-network

volumes:
  joomla_data:
    driver: local
  mariadb_data:
    driver: local
  joomla_php_tmp:
    driver: local

networks:
  joomla-network:
    driver: bridge